### ISSUE TITLE
Azure dataBrick spark version 2.3 is depricated.

### ISSUE THREAD

**Issue by stephenhallfr-zz** [Azure/spark-cdm#2]
Hi this connector can not longuer be used as the Azure Databrick with Spark 2.3 is not available anymore

**Comment by sscrawfo** [comment]
Check out the Spark24 branch, the jar there will work with Spark 2.4

**Comment by billgib** [comment]
The code to support Spark 2.4 has been checked in to the master branch.  This issue can be closed.
